// Each record is intentionally content-only so the collection can grow without changing the UI.
export const animals = [
  { id:"dog", en:"Dog", zh:"小狗", category:"农场与伙伴", wiki:"Dog", emoji:"🐶" },
  { id:"cat", en:"Cat", zh:"小猫", category:"农场与伙伴", wiki:"Cat", emoji:"🐱" },
  { id:"horse", en:"Horse", zh:"马", category:"农场与伙伴", wiki:"Horse", emoji:"🐴" },
  { id:"cow", en:"Cow", zh:"奶牛", category:"农场与伙伴", wiki:"Cattle", emoji:"🐮" },
  { id:"sheep", en:"Sheep", zh:"绵羊", category:"农场与伙伴", wiki:"Sheep", emoji:"🐑" },
  { id:"goat", en:"Goat", zh:"山羊", category:"农场与伙伴", wiki:"Goat", emoji:"🐐" },
  { id:"pig", en:"Pig", zh:"小猪", category:"农场与伙伴", wiki:"Pig", emoji:"🐷" },
  { id:"chicken", en:"Chicken", zh:"小鸡", category:"农场与伙伴", wiki:"Chicken", emoji:"🐔" },
  { id:"duck", en:"Duck", zh:"鸭子", category:"农场与伙伴", wiki:"Duck", emoji:"🦆" },
  { id:"rabbit", en:"Rabbit", zh:"兔子", category:"农场与伙伴", wiki:"Rabbit", emoji:"🐰" },

  { id:"elephant", en:"Elephant", zh:"大象", category:"草原与丛林", wiki:"African bush elephant", emoji:"🐘" },
  { id:"lion", en:"Lion", zh:"狮子", category:"草原与丛林", wiki:"Lion", emoji:"🦁" },
  { id:"tiger", en:"Tiger", zh:"老虎", category:"草原与丛林", wiki:"Tiger", emoji:"🐯" },
  { id:"giraffe", en:"Giraffe", zh:"长颈鹿", category:"草原与丛林", wiki:"Giraffe", emoji:"🦒" },
  { id:"zebra", en:"Zebra", zh:"斑马", category:"草原与丛林", wiki:"Zebra", emoji:"🦓" },
  { id:"monkey", en:"Monkey", zh:"猴子", category:"草原与丛林", wiki:"Monkey", emoji:"🐵" },
  { id:"gorilla", en:"Gorilla", zh:"大猩猩", category:"草原与丛林", wiki:"Gorilla", emoji:"🦍" },
  { id:"chimpanzee", en:"Chimpanzee", zh:"黑猩猩", category:"草原与丛林", wiki:"Chimpanzee", emoji:"🐒" },
  { id:"hippo", en:"Hippo", zh:"河马", category:"草原与丛林", wiki:"Hippopotamus", emoji:"🦛" },
  { id:"rhino", en:"Rhino", zh:"犀牛", category:"草原与丛林", wiki:"Rhinoceros", emoji:"🦏" },
  { id:"crocodile", en:"Crocodile", zh:"鳄鱼", category:"草原与丛林", wiki:"Crocodile", emoji:"🐊" },
  { id:"cheetah", en:"Cheetah", zh:"猎豹", category:"草原与丛林", wiki:"Cheetah", emoji:"🐆" },
  { id:"leopard", en:"Leopard", zh:"花豹", category:"草原与丛林", wiki:"Leopard", emoji:"🐆" },
  { id:"brown-bear", en:"Brown Bear", zh:"棕熊", category:"草原与丛林", wiki:"Brown bear", emoji:"🐻" },
  { id:"panda", en:"Giant Panda", zh:"大熊猫", category:"草原与丛林", wiki:"Giant panda", emoji:"🐼" },

  { id:"wolf", en:"Wolf", zh:"狼", category:"森林与寒地", wiki:"Wolf", emoji:"🐺" },
  { id:"fox", en:"Fox", zh:"狐狸", category:"森林与寒地", wiki:"Red fox", emoji:"🦊" },
  { id:"deer", en:"Deer", zh:"鹿", category:"森林与寒地", wiki:"Deer", emoji:"🦌" },
  { id:"moose", en:"Moose", zh:"驼鹿", category:"森林与寒地", wiki:"Moose", emoji:"🫎" },
  { id:"squirrel", en:"Squirrel", zh:"松鼠", category:"森林与寒地", wiki:"Squirrel", emoji:"🐿️" },
  { id:"hedgehog", en:"Hedgehog", zh:"刺猬", category:"森林与寒地", wiki:"Hedgehog", emoji:"🦔" },
  { id:"raccoon", en:"Raccoon", zh:"浣熊", category:"森林与寒地", wiki:"Raccoon", emoji:"🦝" },
  { id:"kangaroo", en:"Kangaroo", zh:"袋鼠", category:"森林与寒地", wiki:"Kangaroo", emoji:"🦘" },
  { id:"koala", en:"Koala", zh:"考拉", category:"森林与寒地", wiki:"Koala", emoji:"🐨" },
  { id:"polar-bear", en:"Polar Bear", zh:"北极熊", category:"森林与寒地", wiki:"Polar bear", emoji:"🐻‍❄️" },
  { id:"otter", en:"Otter", zh:"水獭", category:"森林与寒地", wiki:"Otter", emoji:"🦦" },
  { id:"penguin", en:"Penguin", zh:"企鹅", category:"森林与寒地", wiki:"Penguin", emoji:"🐧" },

  { id:"owl", en:"Owl", zh:"猫头鹰", category:"鸟儿朋友", wiki:"Owl", emoji:"🦉" },
  { id:"eagle", en:"Eagle", zh:"鹰", category:"鸟儿朋友", wiki:"Eagle", emoji:"🦅" },
  { id:"parrot", en:"Parrot", zh:"鹦鹉", category:"鸟儿朋友", wiki:"Parrot", emoji:"🦜" },
  { id:"flamingo", en:"Flamingo", zh:"火烈鸟", category:"鸟儿朋友", wiki:"Flamingo", emoji:"🦩" },
  { id:"peacock", en:"Peacock", zh:"孔雀", category:"鸟儿朋友", wiki:"Peafowl", emoji:"🦚" },
  { id:"swan", en:"Swan", zh:"天鹅", category:"鸟儿朋友", wiki:"Swan", emoji:"🦢" },
  { id:"ostrich", en:"Ostrich", zh:"鸵鸟", category:"鸟儿朋友", wiki:"Common ostrich", emoji:"🐦" },
  { id:"toucan", en:"Toucan", zh:"巨嘴鸟", category:"鸟儿朋友", wiki:"Toucan", emoji:"🐦" },
  { id:"woodpecker", en:"Woodpecker", zh:"啄木鸟", category:"鸟儿朋友", wiki:"Woodpecker", emoji:"🐦" },
  { id:"hummingbird", en:"Hummingbird", zh:"蜂鸟", category:"鸟儿朋友", wiki:"Hummingbird", emoji:"🐦" },

  { id:"dolphin", en:"Dolphin", zh:"海豚", category:"海洋动物", wiki:"Dolphin", emoji:"🐬" },
  { id:"whale", en:"Whale", zh:"鲸鱼", category:"海洋动物", wiki:"Whale", emoji:"🐋" },
  { id:"blue-whale", en:"Blue Whale", zh:"蓝鲸", category:"海洋动物", wiki:"Blue whale", emoji:"🐋" },
  { id:"shark", en:"Shark", zh:"鲨鱼", category:"海洋动物", wiki:"Shark", emoji:"🦈" },
  { id:"octopus", en:"Octopus", zh:"章鱼", category:"海洋动物", wiki:"Octopus", emoji:"🐙" },
  { id:"sea-turtle", en:"Sea Turtle", zh:"海龟", category:"海洋动物", wiki:"Sea turtle", emoji:"🐢" },
  { id:"seal", en:"Seal", zh:"海豹", category:"海洋动物", wiki:"Seal", emoji:"🦭" },
  { id:"sea-lion", en:"Sea Lion", zh:"海狮", category:"海洋动物", wiki:"Sea lion", emoji:"🦭" },
  { id:"clownfish", en:"Clownfish", zh:"小丑鱼", category:"海洋动物", wiki:"Clownfish", emoji:"🐠" },
  { id:"seahorse", en:"Seahorse", zh:"海马", category:"海洋动物", wiki:"Seahorse", emoji:"🐴" },
  { id:"jellyfish", en:"Jellyfish", zh:"水母", category:"海洋动物", wiki:"Jellyfish", emoji:"🪼" },
  { id:"crab", en:"Crab", zh:"螃蟹", category:"海洋动物", wiki:"Crab", emoji:"🦀" },
  { id:"starfish", en:"Starfish", zh:"海星", category:"海洋动物", wiki:"Starfish", emoji:"⭐" },
  { id:"stingray", en:"Stingray", zh:"魟鱼", category:"海洋动物", wiki:"Stingray", emoji:"🐟" },

  { id:"frog", en:"Frog", zh:"青蛙", category:"爬行与两栖", wiki:"Frog", emoji:"🐸" },
  { id:"toad", en:"Toad", zh:"蟾蜍", category:"爬行与两栖", wiki:"Toad", emoji:"🐸" },
  { id:"snake", en:"Snake", zh:"蛇", category:"爬行与两栖", wiki:"Snake", emoji:"🐍" },
  { id:"lizard", en:"Lizard", zh:"蜥蜴", category:"爬行与两栖", wiki:"Lizard", emoji:"🦎" },
  { id:"chameleon", en:"Chameleon", zh:"变色龙", category:"爬行与两栖", wiki:"Chameleon", emoji:"🦎" },
  { id:"tortoise", en:"Tortoise", zh:"陆龟", category:"爬行与两栖", wiki:"Tortoise", emoji:"🐢" },
  { id:"turtle", en:"Turtle", zh:"乌龟", category:"爬行与两栖", wiki:"Turtle", emoji:"🐢" },
  { id:"iguana", en:"Iguana", zh:"鬣蜥", category:"爬行与两栖", wiki:"Iguana", emoji:"🦎" },
  { id:"gecko", en:"Gecko", zh:"壁虎", category:"爬行与两栖", wiki:"Gecko", emoji:"🦎" },
  { id:"salamander", en:"Salamander", zh:"蝾螈", category:"爬行与两栖", wiki:"Salamander", emoji:"🦎" },

  { id:"butterfly", en:"Butterfly", zh:"蝴蝶", category:"小小昆虫", wiki:"Butterfly", emoji:"🦋" },
  { id:"bee", en:"Bee", zh:"蜜蜂", category:"小小昆虫", wiki:"Bee", emoji:"🐝" },
  { id:"ladybug", en:"Ladybug", zh:"瓢虫", category:"小小昆虫", wiki:"Coccinellidae", emoji:"🐞" },
  { id:"ant", en:"Ant", zh:"蚂蚁", category:"小小昆虫", wiki:"Ant", emoji:"🐜" },
  { id:"spider", en:"Spider", zh:"蜘蛛", category:"小小昆虫", wiki:"Spider", emoji:"🕷️" },
  { id:"dragonfly", en:"Dragonfly", zh:"蜻蜓", category:"小小昆虫", wiki:"Dragonfly", emoji:"🪰" },
  { id:"snail", en:"Snail", zh:"蜗牛", category:"小小昆虫", wiki:"Snail", emoji:"🐌" },
  { id:"caterpillar", en:"Caterpillar", zh:"毛毛虫", category:"小小昆虫", wiki:"Caterpillar", emoji:"🐛" },
  { id:"grasshopper", en:"Grasshopper", zh:"蚱蜢", category:"小小昆虫", wiki:"Grasshopper", emoji:"🦗" }
];
